# Generated by Django 4.2 on 2026-05-06 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('clave', models.CharField(max_length=15)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('appat', models.CharField(max_length=20)),
                ('apmat', models.CharField(max_length=20)),
                ('matricula', models.IntegerField()),
                ('curp', models.CharField(max_length=20)),
                ('fotografia', models.ImageField(blank=True, null=True, upload_to='fotografias/')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mi_aplicacion.carrera')),
            ],
        ),
    ]
